name: hkid_validator_web_demo
description: HKID Validator used to validate the HKID and generate the validate HKID through the hkid_validator packages. This is a Single Page Application (SPA) which used Flutter to develop.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.2.0
  hkid_validator:
    # When depending on this package from a real application you should use:
    #   hkid_validator: ^x.y.z
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  get: ^4.6.5
  flutter_localizations:
    sdk: flutter
  get_storage: ^2.0.3
  sembast_web: ^2.0.1+1
  sembast: ">=3.1.1 <5.0.0"
  idb_shim: ">=2.0.1 <4.0.0"
  syncfusion_flutter_xlsio: ^20.2.48-beta
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
  fonts: