name: hkid_validator
description: A HKID Validator and Generator, written by pure dart and foundamental library. Through this library you would esaily validate your HKID esaily. This library support all the platform of flutter and dart.
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  test: ^1.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
