name: hkid_validator
description: An HKID Validator and Generator, written by a pure dart. Through this library, you would easily validate your HKID quickly.
repository: https://github.com/hkk97/hkid_validator/tree/main
version: 0.0.5

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  test: ^1.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
