name: GitHubPageCICD

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set Flutter version
        uses: subosito/flutter-action@v2.2.0
        with:
          flutter-version: "${{ github.event.inputs.flutter_version }}"
      - name: Install packages
        run: |
          flutter config --enable-web
          cd example
          flutter pub get
      - name: Flutter build Web
        run: |
          cd example
          flutter build web --web-renderer html --no-sound-null-safety --dart-define=ENV=PROD -dart-define=FLUTTER_WEB_USE_SKIA=true
          mv -vi /home/runner/work/hkid_validator/hkid_validator/example/assets/demo /home/runner/work/hkid_validator/hkid_validator/example/build/web/assets/assets/demo
      - name: Deploy to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: example/build/web
          force_orphan: true
